# -*- coding: utf-8 -*-

name: Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

jobs:

  BuildDocs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Checkout this Repo
      uses: actions/checkout@v2
      with:
        path: pyadic
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx
    - name: Build docs
      run: |
        cd sphinx
        make github
    - name: Commit docs to gh-pages branch
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        file_pattern: docs/*
        commit_message: "Automatic docs update"
        branch: gh-pages
        repository: .
