# -*- coding: utf-8 -*-

name: Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

jobs:

  BuildDocs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Checkout this Repo
      uses: actions/checkout@v3
      with:
        path: pyadic
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx-rtd-theme
    - name: Build docs
      run: |
        cd sphinx
        make github
        git status
    - name: Check the folder status
      run: |
        echo "pwd"
        pwd
        echo "ls"
        ls
        echo "ls docs/"
        ls docs/
    - name: setup git config
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
    - name: Commit docs to gh-pages branch
      run: |
        echo "fetching..."
        git status
        git fetch
        git status
        git reset --hard
        echo "checking out gh-pages..."
        git checkout gh-pages
        touch docs/.nojekyll
        git status
        git checkout main README.md
        git add -f docs/.nojekyll
        git add -f docs/.buildinfo
        git add README.md docs/*
        echo "committing changes if needed..."
        git status
        if ! git diff-index --quiet HEAD; then
          git commit -m "Automated docs update."
          git push origin gh-pages
        fi
